baseURL = "https://wenrui-jiang.github.io/"
title = "Jiang Wenrui's Website"
theme = "wenruijiang"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

languageCode = "en"

[params]
title = "I'm Jiang Wenrui"
author = "Jiang Wenrui"
description = "Call me Leo"
profilePicture = "images/live.jpg"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[languages]

[languages.en]
languageName = "English"
languageCode = "en"
contentDir = "content/english"
title = "Jiang Wenrui's Website"
weight = 1

[languages.zh]
languageName = "中文"
languageCode = "zh"
contentDir = "content/Chienese"
title = "蒋文睿的网站"
weight = 2
