baseURL = "https://wenrui-jiang.github.io/"

languageCode = "en"
title = "Jiang Wenrui's Website"

theme = "wenruijiang"


[params]
title = "I'm Jiang Wenrui"
author = "Jiang Wenrui"
description = "Call me Leo"
profilePicture = "images/live.jpg"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

#[module]
#[[module.imports]]
#path = "github.com/Vegetablebird086/wenruijiang.github.io"
