# theme.toml template for a Hugo theme

name = "Wenrui personal Website"
license = "MIT"
#licenselink = "https://github.com/yourusername/yourrepo/blob/master/LICENSE"
description = "Master student in BJTU."
homepage = "https://github.com/Vegetablebird086/wenruijiang.github.io/"
#demosite = "https://your-website-url.com/"
tags = ["blog", "responsive", "clean", "minimalist", "minimal", "personal", "dark"]
features = ["blog", "seo", "responsive", "mobile", "disqus", "fontawesome", "analytics", "math"]
min_version = "0.128.0"

[author]
name = "Jiang Wenrui"
homepage = "https://wenruijiang.github.io"

# You can keep the original section if you want to credit the original theme
[original]
author = "Alexander Bilz"
homepage = "https://alexbilz.com"
repo = "https://github.com/lxndrblz/anatole"